### ISSUE TITLE
Write perceived media bias function

### ISSUE THREAD

**Issue by postnubilaphoebus** [GeorgGroenendaal/A04-Media-agents-in-DIAL#20]
Perceived media bias determines how people agents react to media agents influencing them.
0 means they let themselves get influenced completely, 0.5 means they do not let themselves get influenced at all, and 1 means they move in the opposite direction of the media agent opinion.

- [x] function init-perceived-media-bias

- [ ] adjust-influence-by-perceived-media-bias

**Comment by GeorgGroenendaal** [comment]
closed with #25
