### ISSUE TITLE
Adjust normal distribution functions

### ISSUE THREAD

**Issue by postnubilaphoebus** [GeorgGroenendaal/A04-Media-agents-in-DIAL#23]
The normal distribution functions we use so far in the code have a couple of issues.
I recommend reading this stackoverflow post as a primer:
https://stackoverflow.com/questions/20230685/netlogo-how-to-make-sure-a-variable-stays-in-a-defined-range?fbclid=IwAR3Cd00LSSRzOnTe7sysbUaYzPvbaFBq1N9JtpFLPpFh3EKz_2_S3TItDI8
The cap function (used for generatemediaopinions) creates spikes at the boundaries of the range (first picture)
The function I use for reputation-based-prob has a lower standard deviation toward more extreme reputation values (close to 0 or 1). **Ideally, we should choose the third option mentioned in the post (triangular distribution)**

- [x] Adjust reputation-based-prob

- [x] Adjust generateopinionsmedia

**Comment by GeorgGroenendaal** [comment]
Closed with PR #25
